/**
 * Loader tests. The atsi/difficulty cases are ported from the legacy
 * `tests/test_loader.py`; the parity test parses the committed synthetic
 * fixture via exceljs, runs the TS loader, and asserts the result matches the
 * oracle snapshot generated by `verification/gen_loader_snapshot.py`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import {
  atsiCombined,
  cleanStudentReports,
  cleanStudentResults,
  detectDomainAndYear,
  difficultyBand,
  parseWorkbook,
} from "../src/index";

const here = dirname(fileURLToPath(import.meta.url));
const fixtureBytes = readFileSync(join(here, "fixtures/synthetic_raw_2026.xlsx"));
const snapshot = JSON.parse(
  readFileSync(join(here, "fixtures/loader_snapshot.json"), "utf8"),
) as {
  domain: string;
  yearLevel: number;
  participants: number;
  totalStudents: number;
  studentReports: unknown[];
  studentResults: unknown[];
};

describe("atsiCombined", () => {
  it("Aboriginal-only → ATSI", () => {
    expect(atsiCombined("Aboriginal but not Torres Strait Islander origin")).toBe("ATSI");
  });
  it("Torres Strait Islander → ATSI", () => {
    expect(atsiCombined("Torres Strait Islander but not Aboriginal origin")).toBe("ATSI");
  });
  it("both → ATSI", () => {
    expect(atsiCombined("Both Aboriginal and Torres Strait Islander origin")).toBe("ATSI");
  });
  it("the specific 'Neither' string → Non-ATSI", () => {
    expect(atsiCombined("Neither Aboriginal nor Torres Strait Islander origin")).toBe("Non-ATSI");
  });
  it("null → Not reported", () => {
    expect(atsiCombined(null)).toBe("Not reported");
  });
});

describe("difficultyBand", () => {
  it("below 480", () => expect(difficultyBand(450)).toBe("Below 480"));
  it("lower boundary 480 inclusive", () => expect(difficultyBand(480)).toBe("480-580"));
  it("upper boundary 580 inclusive", () => expect(difficultyBand(580)).toBe("480-580"));
  it("above 580", () => expect(difficultyBand(600)).toBe("Above 580"));
  it("null → Unknown", () => expect(difficultyBand(null)).toBe("Unknown"));
});

describe("loader parity with the Python oracle (synthetic fixture)", () => {
  it("parses + cleans Student Reports identically to the oracle", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    expect(reports).toEqual(snapshot.studentReports);
  });

  it("parses + cleans Student Results Table identically to the oracle", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const results = cleanStudentResults(wb.sheet("Student Results Table")!);
    expect(results).toEqual(snapshot.studentResults);
  });

  it("detects domain + year level and participant counts", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    const { domain, yearLevel } = detectDomainAndYear(reports);
    expect(domain).toBe(snapshot.domain);
    expect(yearLevel).toBe(snapshot.yearLevel);

    const participants = reports.filter((r) => r.participationCode === "Participated").length;
    expect(participants).toBe(snapshot.participants);
    expect(reports).toHaveLength(snapshot.totalStudents);
  });

  it("blank Local student ID falls back to {studentId}* for display only", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    const charlie = reports.find((r) => r.studentId === "TESTPSI003")!;
    expect(charlie.localStudentId).toBeNull(); // dropped from cross-year keying
    expect(charlie.localStudentIdDisplay).toBe("TESTPSI003*");
  });
});
