/**
 * Loader tests. The atsi/difficulty cases are ported from the legacy
 * `tests/test_loader.py`; the parity test parses the committed synthetic
 * fixture via exceljs, runs the TS loader, and asserts the result matches the
 * oracle snapshot generated by `verification/gen_loader_snapshot.py`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import {
  atsiCombined,
  buildStore,
  cleanStudentReports,
  cleanStudentResults,
  detectDomainAndYear,
  detectYearOfTestFromName,
  difficultyBand,
  inspectWorkbook,
  loadStoreFromFiles,
  parseWorkbook,
  type ParsedWorkbook,
} from "../src/index";

const here = dirname(fileURLToPath(import.meta.url));
const fixtureBytes = readFileSync(join(here, "fixtures/synthetic_raw_2026.xlsx"));
const snapshot = JSON.parse(
  readFileSync(join(here, "fixtures/loader_snapshot.json"), "utf8"),
) as {
  domain: string;
  yearLevel: number;
  participants: number;
  totalStudents: number;
  studentReports: unknown[];
  studentResults: unknown[];
};

describe("atsiCombined", () => {
  it("Aboriginal-only → ATSI", () => {
    expect(atsiCombined("Aboriginal but not Torres Strait Islander origin")).toBe("ATSI");
  });
  it("Torres Strait Islander → ATSI", () => {
    expect(atsiCombined("Torres Strait Islander but not Aboriginal origin")).toBe("ATSI");
  });
  it("both → ATSI", () => {
    expect(atsiCombined("Both Aboriginal and Torres Strait Islander origin")).toBe("ATSI");
  });
  it("the specific 'Neither' string → Non-ATSI", () => {
    expect(atsiCombined("Neither Aboriginal nor Torres Strait Islander origin")).toBe("Non-ATSI");
  });
  it("null → Not reported", () => {
    expect(atsiCombined(null)).toBe("Not reported");
  });
});

describe("difficultyBand", () => {
  it("below 480", () => expect(difficultyBand(450)).toBe("Below 480"));
  it("lower boundary 480 inclusive", () => expect(difficultyBand(480)).toBe("480-580"));
  it("upper boundary 580 inclusive", () => expect(difficultyBand(580)).toBe("480-580"));
  it("above 580", () => expect(difficultyBand(600)).toBe("Above 580"));
  it("null → Unknown", () => expect(difficultyBand(null)).toBe("Unknown"));
});

describe("loader parity with the Python oracle (synthetic fixture)", () => {
  it("parses + cleans Student Reports identically to the oracle", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    expect(reports).toEqual(snapshot.studentReports);
  });

  it("parses + cleans Student Results Table identically to the oracle", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const results = cleanStudentResults(wb.sheet("Student Results Table")!);
    expect(results).toEqual(snapshot.studentResults);
  });

  it("detects domain + year level and participant counts", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    const { domain, yearLevel } = detectDomainAndYear(reports);
    expect(domain).toBe(snapshot.domain);
    expect(yearLevel).toBe(snapshot.yearLevel);

    const participants = reports.filter((r) => r.participationCode === "Participated").length;
    expect(participants).toBe(snapshot.participants);
    expect(reports).toHaveLength(snapshot.totalStudents);
  });

  it("blank Local student ID falls back to {studentId}* for display only", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const reports = cleanStudentReports(wb.sheet("Student Reports")!);
    const charlie = reports.find((r) => r.studentId === "TESTPSI003")!;
    expect(charlie.localStudentId).toBeNull(); // dropped from cross-year keying
    expect(charlie.localStudentIdDisplay).toBe("TESTPSI003*");
  });
});

describe("detectYearOfTestFromName", () => {
  it("extracts the year from a folder name", () => {
    expect(detectYearOfTestFromName("Naplan 2026")).toBe(2026);
  });
  it("extracts the year from a file name", () => {
    expect(detectYearOfTestFromName("SSSR Extract Reading 2024.xlsx")).toBe(2024);
  });
  it("returns null when no year is present", () => {
    expect(detectYearOfTestFromName("SSSR Extract Reading.xlsx")).toBeNull();
  });
});

describe("buildStore", () => {
  /** Build a single-sheet ParsedWorkbook by reusing a real parsed sheet. */
  function oneSheet(wb: ParsedWorkbook, name: string): ParsedWorkbook {
    const sheet = wb.sheet(name);
    return { sheetNames: [name], sheet: (n) => (n === name ? sheet : null) };
  }

  it("registers a full (2026-format) workbook as one entry", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const { store, skipped } = buildStore([
      { filename: "SSSR Extract Reading 2026.xlsx", yearOfTest: 2026, workbook: wb },
    ]);
    expect(skipped).toEqual([]);
    expect(store.size).toBe(1);
    const entry = store.get("2026|7|Reading")!;
    expect(entry.domain).toBe("Reading");
    expect(entry.yearLevel).toBe(7);
    expect(entry.participants).toBe(5);
    expect(entry.totalStudents).toBe(6);
  });

  it("pairs a 2025-format split (Reports file + Results file)", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const { store, skipped } = buildStore([
      {
        filename: "Student Reports Reading 2025.xlsx",
        yearOfTest: 2025,
        workbook: oneSheet(wb, "Student Reports"),
      },
      {
        filename: "Student Results Table Reading 2025.xlsx",
        yearOfTest: 2025,
        workbook: oneSheet(wb, "Student Results Table"),
      },
    ]);
    expect(skipped).toEqual([]);
    expect(store.size).toBe(1);
    const entry = store.get("2025|7|Reading")!;
    expect(entry.participants).toBe(5);
    expect(entry.sourceFilename).toContain(" + ");
  });

  it("skips a split file with no pairing partner", async () => {
    const wb = await parseWorkbook(fixtureBytes);
    const { store, skipped } = buildStore([
      {
        filename: "Student Reports Reading 2025.xlsx",
        yearOfTest: 2025,
        workbook: oneSheet(wb, "Student Reports"),
      },
    ]);
    expect(store.size).toBe(0);
    expect(skipped).toHaveLength(1);
    expect(skipped[0]!.reason).toContain("missing Student Results Table");
  });
});

describe("inspectWorkbook (import-screen classifier)", () => {
  it("recognises a full 2026 workbook (both sheets)", async () => {
    const res = await inspectWorkbook(fixtureBytes);
    expect(res.status).toBe("ok");
    if (res.status === "ok") {
      expect(res.sheets).toBe("full");
      expect(res.domain).toBe("Reading");
      expect(res.yearLevel).toBe(7);
    }
  });

  it("recognises a reports-only workbook as a 2025 split half", async () => {
    const reportsOnly = readFileSync(join(here, "fixtures/synthetic_y9_2026_reading.xlsx"));
    const res = await inspectWorkbook(reportsOnly);
    expect(res.status).toBe("ok");
    if (res.status === "ok") {
      expect(res.sheets).toBe("reports");
      expect(res.yearLevel).toBe(9);
      expect(res.domain).toBe("Reading");
    }
  });

  it("rejects unreadable bytes with a plain reason", async () => {
    const res = await inspectWorkbook(new Uint8Array([1, 2, 3, 4]));
    expect(res.status).toBe("rejected");
    if (res.status === "rejected") expect(res.reason).toMatch(/read this file/i);
  });
});

describe("loadStoreFromFiles — parse reuse", () => {
  const RELPATH = "Naplan 2026/synthetic_raw_2026.xlsx";

  it("uses a supplied pre-parsed workbook instead of re-parsing the bytes", async () => {
    const parsed = await parseWorkbook(fixtureBytes);
    let sheetReads = 0;
    const counting: ParsedWorkbook = {
      sheetNames: parsed.sheetNames,
      sheet: (n) => {
        sheetReads += 1;
        return parsed.sheet(n);
      },
    };

    const { store } = await loadStoreFromFiles(
      [
        {
          name: "synthetic_raw_2026.xlsx",
          relativePath: RELPATH,
          bytes: fixtureBytes,
          yearOfTest: 2026,
        },
      ],
      new Map([[RELPATH, counting]]),
    );

    expect(store.size).toBe(1);
    // Proves the CACHED workbook was the one consumed — a re-parse would have
    // produced its own ParsedWorkbook and left this counter at zero.
    expect(sheetReads).toBeGreaterThan(0);
  });

  it("still parses from bytes when no cache entry exists", async () => {
    const { store } = await loadStoreFromFiles([
      {
        name: "synthetic_raw_2026.xlsx",
        relativePath: RELPATH,
        bytes: fixtureBytes,
        yearOfTest: 2026,
      },
    ]);
    expect(store.size).toBe(1);
  });
});
