/**
 * Section computation parity (Sections 1, 2, 7). Parses the synthetic fixture
 * and asserts the ported helpers reproduce the oracle snapshot generated by
 * `verification/gen_sections_snapshot.py`.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { beforeAll, describe, expect, it } from "vitest";
import {
  classDistribution,
  cleanStudentReports,
  parseWorkbook,
  participationBreakdown,
  participationSummary,
  proficiencyCounts,
  proficiencyPercentages,
  type StudentReportRow,
} from "../src/index";

const here = dirname(fileURLToPath(import.meta.url));
const snap = JSON.parse(
  readFileSync(join(here, "fixtures/sections_snapshot.json"), "utf8"),
) as {
  participation: {
    breakdown: { Participated: number; Absent: number; Withdrawn: number };
    total: number;
    participated: number;
    rate: number;
  };
  proficiency: {
    counts: Record<string, number>;
    percentages: Record<string, number>;
  };
  classDistribution: Array<{ classGroup: string; n: number; percentages: Record<string, number> }>;
};

let reports: StudentReportRow[];
beforeAll(async () => {
  const wb = await parseWorkbook(readFileSync(join(here, "fixtures/synthetic_raw_2026.xlsx")));
  reports = cleanStudentReports(wb.sheet("Student Reports")!);
});

describe("Section 1 — participation", () => {
  it("breakdown matches the oracle", () => {
    const b = participationBreakdown(reports);
    expect(b.participated).toBe(snap.participation.breakdown.Participated);
    expect(b.absent).toBe(snap.participation.breakdown.Absent);
    expect(b.withdrawn).toBe(snap.participation.breakdown.Withdrawn);
  });
  it("summary (total / participated / rate) matches the oracle", () => {
    const s = participationSummary(reports);
    expect(s.total).toBe(snap.participation.total);
    expect(s.participated).toBe(snap.participation.participated);
    expect(s.rate).toBeCloseTo(snap.participation.rate, 10);
  });
});

describe("Section 2 — proficiency", () => {
  it("counts match the oracle", () => {
    expect(proficiencyCounts(reports)).toEqual(snap.proficiency.counts);
  });
  it("percentages match the oracle", () => {
    const pct = proficiencyPercentages(reports);
    for (const [lvl, expected] of Object.entries(snap.proficiency.percentages)) {
      expect(pct[lvl as keyof typeof pct]).toBeCloseTo(expected, 10);
    }
  });
});

describe("Section 7 — class distribution", () => {
  it("matches the oracle per class group", () => {
    const dist = classDistribution(reports);
    expect(dist).toHaveLength(snap.classDistribution.length);
    for (let i = 0; i < dist.length; i++) {
      const got = dist[i]!;
      const want = snap.classDistribution[i]!;
      expect(got.classGroup).toBe(want.classGroup);
      expect(got.n).toBe(want.n);
      for (const [lvl, expected] of Object.entries(want.percentages)) {
        expect(got.percentages[lvl as keyof typeof got.percentages]).toBeCloseTo(expected, 10);
      }
    }
  });
});
